// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQN6fXEwtUBXS9tGzv5KC3Z6M0RmSJ4sQ',
    appId: '1:1064068098919:web:3e8e26ea901393754b9dc2',
    messagingSenderId: '1064068098919',
    projectId: 'hotelio-6d757',
    authDomain: 'hotelio-6d757.firebaseapp.com',
    storageBucket: 'hotelio-6d757.appspot.com',
    measurementId: 'G-0938R7XQ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU4yQxZT_SiPvEHYmeAXBbsTOnrXRHL8s',
    appId: '1:1064068098919:android:31d6783d5951c3844b9dc2',
    messagingSenderId: '1064068098919',
    projectId: 'hotelio-6d757',
    storageBucket: 'hotelio-6d757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCUe252Lan5IwUlFuTWuNVp-gm9-1mzk',
    appId: '1:1064068098919:ios:c5a2fb618bc05ca14b9dc2',
    messagingSenderId: '1064068098919',
    projectId: 'hotelio-6d757',
    storageBucket: 'hotelio-6d757.appspot.com',
    iosClientId: '1064068098919-h0uk6ljoaemr00egm83vflf09becblsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGCUe252Lan5IwUlFuTWuNVp-gm9-1mzk',
    appId: '1:1064068098919:ios:db14ffc9009f2e154b9dc2',
    messagingSenderId: '1064068098919',
    projectId: 'hotelio-6d757',
    storageBucket: 'hotelio-6d757.appspot.com',
    iosClientId: '1064068098919-ap9n5b34ei78m1700o5iqdbv32dsrfrc.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio3.RunnerTests',
  );
}
